export type WordItem = {
  word:string;
  clue:string;
}

export const WORDS:{
  easy: WordItem[];
  medium:WordItem[];
  hard: WordItem[];

} = {
  
  easy: [
  { word: "cat", clue: "A small domesticated animal that says meow" },
  { word: "dog", clue: "A loyal animal often kept as a pet" },
  { word: "sun", clue: "The star at the center of our solar system" },
  { word: "moon", clue: "The natural satellite of the Earth" },
  { word: "star", clue: "A bright object in the night sky" },
  { word: "tree", clue: "A tall plant with a trunk and branches" },
  { word: "book", clue: "Pages bound together for reading" },
  { word: "fish", clue: "An animal that lives in water and swims" },
  { word: "bird", clue: "An animal with feathers that can fly" },
  { word: "milk", clue: "A white drink that comes from cows" },
  { word: "apple", clue: "A round fruit often red or green" },
  { word: "bread", clue: "A baked food made from flour" },
  { word: "water", clue: "A clear liquid essential for life" },
  { word: "chair", clue: "Furniture used for sitting" },
  { word: "table", clue: "Furniture with a flat top and legs" },
  { word: "clock", clue: "An object that tells time" },
  { word: "door", clue: "You open this to enter a room" },
  { word: "bed", clue: "Furniture used for sleeping" },
  { word: "shoe", clue: "You wear this on your foot" },
  { word: "phone", clue: "A device used to call people" },
  { word: "pen", clue: "Used for writing with ink" },
  { word: "paper", clue: "Used for writing or drawing" },
  { word: "cup", clue: "Used for drinking liquids" },
  { word: "plate", clue: "Used to hold food" },
  { word: "spoon", clue: "Used to eat or stir food" },
  { word: "house", clue: "A building where people live" },
  { word: "road", clue: "A path for cars and people" },
  { word: "car", clue: "A vehicle with four wheels" },
  { word: "bus", clue: "A large vehicle for many passengers" },
  { word: "bike", clue: "A two-wheeled vehicle you pedal" },
  { word: "hat", clue: "Something you wear on your head" },
  { word: "shirt", clue: "Clothing worn on the upper body" },
  { word: "pants", clue: "Clothing worn on the legs" },
  { word: "sock", clue: "Worn on the foot inside shoes" },
  { word: "rain", clue: "Water that falls from clouds" },
  { word: "snow", clue: "Frozen rain that falls in winter" },
  { word: "wind", clue: "Moving air" },
  { word: "fire", clue: "Produces heat and light" },
  { word: "ice", clue: "Frozen water" },
  { word: "ball", clue: "A round object used in games" },
  { word: "game", clue: "Something played for fun" },
  { word: "toy", clue: "An object children play with" },
  { word: "baby", clue: "A very young child" },
  { word: "man", clue: "An adult male human" },
  { word: "woman", clue: "An adult female human" },
  { word: "food", clue: "What people eat to survive" },
  { word: "rice", clue: "A common grain food" },
  { word: "egg", clue: "Laid by birds and used as food" },
  { word: "salt", clue: "A white seasoning used in food" },
  { word: "sugar", clue: "A sweet substance" },
  { word: "cake", clue: "A sweet baked dessert" },
  { word: "juice", clue: "A drink made from fruits" },
  { word: "road", clue: "A path for travel" },
  { word: "lamp", clue: "Provides light in a room" },
  { word: "light", clue: "Makes things visible" },
  { word: "dark", clue: "The absence of light" },
  { word: "hand", clue: "Part of the body used to hold things" },
  { word: "foot", clue: "Used for walking" },
  { word: "eye", clue: "Used for seeing" },
  { word: "nose", clue: "Used for smelling" },
  { word: "ear", clue: "Used for hearing" },
  { word: "mouth", clue: "Used for eating and speaking" },
  { word: "face", clue: "The front of the head" },
  { word: "hair", clue: "Grows on the head" },
  { word: "soap", clue: "Used for cleaning" },
  { word: "towel", clue: "Used for drying" },
  { word: "bag", clue: "Used to carry items" },
  { word: "box", clue: "A container with flat sides" },
  { word: "key", clue: "Used to open locks" },
  { word: "lock", clue: "Keeps something closed" },
  { word: "bell", clue: "Makes a ringing sound" },
  { word: "ring", clue: "Jewelry worn on a finger" },
  { word: "map", clue: "Shows locations and directions" },
  { word: "flag", clue: "Represents a country or group" },
  { word: "king", clue: "A male ruler" },
  { word: "queen", clue: "A female ruler" },
  { word: "smile", clue: "A happy facial expression" },
  { word: "laugh", clue: "A sound made when happy" },
  { word: "cry", clue: "To shed tears" },
  { word: "sleep", clue: "What you do to rest" },
  { word: "dream", clue: "Images seen while sleeping" }
],
medium: [
  { word: "planet", clue: "A large object that orbits a star" },
  { word: "memory", clue: "The ability to remember information" },
  { word: "signal", clue: "A message sent to communicate information" },
  { word: "forest", clue: "A large area filled with trees" },
  { word: "machine", clue: "A device that helps do work" },
  { word: "system", clue: "Parts working together as a whole" },
  { word: "program", clue: "Instructions that tell a computer what to do" },
  { word: "battery", clue: "A device that stores electrical energy" },
  { word: "gravity", clue: "The force that pulls objects downward" },
  { word: "pressure", clue: "Force applied over an area" },
  { word: "solution", clue: "An answer to a problem" },
  { word: "network", clue: "Connected computers or systems" },
  { word: "project", clue: "A planned piece of work" },
  { word: "student", clue: "A person who is learning" },
  { word: "formula", clue: "A mathematical or scientific expression" },
  { word: "emotion", clue: "A strong human feeling" },
  { word: "decision", clue: "A choice made after thinking" },
  { word: "creative", clue: "Able to produce original ideas" },
  { word: "internet", clue: "The global system of connected computers" },
  { word: "database", clue: "An organized collection of data" },
  { word: "energy", clue: "The ability to do work" },
  { word: "motion", clue: "The act of moving" },
  { word: "balance", clue: "Equal distribution of weight or force" },
  { word: "control", clue: "The power to influence something" },
  { word: "design", clue: "Planning how something looks or works" },
  { word: "process", clue: "A series of steps to achieve a result" },
  { word: "pattern", clue: "A repeated design or sequence" },
  { word: "logic", clue: "Reasoning based on facts" },
  { word: "method", clue: "A way of doing something" },
  { word: "research", clue: "Careful study to discover information" },
  { word: "history", clue: "The study of past events" },
  { word: "culture", clue: "Beliefs and traditions of a group" },
  { word: "language", clue: "A system used to communicate" },
  { word: "science", clue: "The study of the natural world" },
  { word: "physics", clue: "The study of matter and energy" },
  { word: "chemistry", clue: "The study of substances and reactions" },
  { word: "biology", clue: "The study of living organisms" },
  { word: "economy", clue: "How money and resources are managed" },
  { word: "finance", clue: "The management of money" },
  { word: "market", clue: "A place to buy and sell goods" },
  { word: "product", clue: "Something made to be sold" },
  { word: "quality", clue: "How good something is" },
  { word: "service", clue: "Help provided to others" },
  { word: "digital", clue: "Related to computers or technology" },
  { word: "device", clue: "A tool made for a purpose" },
  { word: "software", clue: "Programs used by a computer" },
  { word: "hardware", clue: "The physical parts of a computer" },
  { word: "security", clue: "Protection from danger or harm" },
  { word: "privacy", clue: "Keeping personal information safe" },
  { word: "update", clue: "A new version with improvements" },
  { word: "feature", clue: "A special function or part" },
  { word: "interface", clue: "Where users interact with a system" },
  { word: "feedback", clue: "Information about performance" },
  { word: "response", clue: "An answer or reaction" },
  { word: "analysis", clue: "Careful examination of details" },
  { word: "strategy", clue: "A plan to achieve a goal" },
  { word: "management", clue: "Organizing and controlling resources" },
  { word: "leadership", clue: "Guiding others" },
  { word: "teamwork", clue: "Working together as a group" },
  { word: "innovation", clue: "Introducing new ideas or methods" },
  { word: "progress", clue: "Movement toward improvement" },
  { word: "efficiency", clue: "Doing work with minimal waste" },
  { word: "resource", clue: "Something useful that can be used" },
  { word: "capacity", clue: "The maximum amount something can hold" },
  { word: "performance", clue: "How well something works" },
  { word: "measurement", clue: "Determining size or quantity" },
  { word: "accuracy", clue: "How correct something is" },
  { word: "prediction", clue: "A statement about the future" },
  { word: "observation", clue: "Careful watching or noticing" },
  { word: "experiment", clue: "A test to discover results" },
  { word: "variable", clue: "A value that can change" },
  { word: "constant", clue: "A value that does not change" },
  { word: "function", clue: "A specific role or purpose" },
  { word: "structure", clue: "How parts are arranged" },
  { word: "framework", clue: "A basic supporting system" }
],
hard: [
  { word: "algorithm", clue: "A step-by-step method for solving a problem" },
  { word: "optimization", clue: "Making something as efficient as possible" },
  { word: "abstraction", clue: "Focusing on key ideas while hiding details" },
  { word: "complexity", clue: "How difficult a system or problem is" },
  { word: "scalability", clue: "Ability to handle growth effectively" },
  { word: "probability", clue: "The likelihood of an event happening" },
  { word: "heuristic", clue: "A practical method for problem-solving" },
  { word: "encryption", clue: "Protecting data by converting it into code" },
  { word: "authentication", clue: "Verifying identity or access" },
  { word: "architecture", clue: "The overall design of a system" },
  { word: "iteration", clue: "Repeating a process multiple times" },
  { word: "validation", clue: "Ensuring correctness or accuracy" },
  { word: "hypothesis", clue: "A testable explanation" },
  { word: "causation", clue: "A cause-and-effect relationship" },
  { word: "epistemology", clue: "The study of knowledge" },
  { word: "metaphysics", clue: "The study of reality and existence" },
  { word: "ontology", clue: "The study of being and categories" },
  { word: "semantics", clue: "The study of meaning in language" },
  { word: "syntax", clue: "Rules for sentence or code structure" },
  { word: "paradigm", clue: "A typical example or model" },
  { word: "simulation", clue: "Imitating a real-world process" },
  { word: "modelling", clue: "Creating a representation of a system" },
  { word: "computation", clue: "Processing information mathematically" },
  { word: "derivative", clue: "A rate of change in calculus" },
  { word: "integral", clue: "A measure of accumulation" },
  { word: "vector", clue: "A quantity with magnitude and direction" },
  { word: "matrix", clue: "A rectangular array of numbers" },
  { word: "eigenvalue", clue: "A special number related to matrices" },
  { word: "entropy", clue: "A measure of disorder" },
  { word: "thermodynamics", clue: "The study of heat and energy" },
  { word: "relativity", clue: "Einstein’s theory of space and time" },
  { word: "quantum", clue: "The smallest unit in physics" },
  { word: "superposition", clue: "Multiple states existing at once" },
  { word: "uncertainty", clue: "Limits to measurement precision" },
  { word: "neuroscience", clue: "The study of the brain and nervous system" },
  { word: "cognition", clue: "Mental processes of thinking and knowing" },
  { word: "consciousness", clue: "Awareness of self and surroundings" },
  { word: "perception", clue: "How the brain interprets sensory input" },
  { word: "optimization", clue: "Finding the best possible solution" },
  { word: "equilibrium", clue: "A state of balance" },
  { word: "differential", clue: "Related to change in variables" },
  { word: "nonlinear", clue: "Not proportional or predictable" },
  { word: "stochastic", clue: "Involving randomness" },
  { word: "deterministic", clue: "Fully predictable outcomes" },
  { word: "causality", clue: "Relationship between cause and effect" },
  { word: "inference", clue: "Drawing conclusions from evidence" },
  { word: "correlation", clue: "A relationship between variables" },
  { word: "regression", clue: "A statistical analysis method" },
  { word: "distribution", clue: "How values are spread" },
  { word: "variance", clue: "Measure of data spread" },
  { word: "deviation", clue: "Difference from the average" },
  { word: "approximation", clue: "A close but not exact value" },
  { word: "convergence", clue: "Approaching a final value" },
  { word: "divergence", clue: "Moving away from a value" },
  { word: "robustness", clue: "Resistance to failure" },
  { word: "redundancy", clue: "Extra components for reliability" },
  { word: "latency", clue: "Delay before a response" },
  { word: "throughput", clue: "Amount processed over time" },
  { word: "bandwidth", clue: "Maximum data transfer rate" },
  { word: "synchronization", clue: "Coordinating events in time" },
  { word: "parallelism", clue: "Doing multiple tasks at once" },
  { word: "concurrency", clue: "Handling many tasks together" },
  { word: "deadlock", clue: "Processes stuck waiting on each other" },
  { word: "virtualization", clue: "Creating virtual versions of systems" },
  { word: "containerization", clue: "Packaging software with dependencies" },
  { word: "orchestration", clue: "Managing automated systems" },
  { word: "deployment", clue: "Releasing software to users" },
  { word: "observability", clue: "Understanding system behavior" },
  { word: "telemetry", clue: "Automatic data collection" },
  { word: "resilience", clue: "Ability to recover from failure" },
  { word: "governance", clue: "Rules and control structures" },
  { word: "ethics", clue: "Moral principles guiding actions" },
  { word: "philosophy", clue: "The study of existence and knowledge" }
]

};