import type { Metadata } from "next";
import {Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sora } from "next/font/google";
import BackgroundWords from "./game/backgroundWords/BackgroundWords";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sora = Sora({subsets:["latin"]})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className="h-full">
      <body
        className={` ${sora.className} ${geistSans.variable} ${geistMono.variable}  antialiased h-full`}
      >
        
        {children}
      </body>
    </html>
  );
}
